DRAFT: first pass integrating June tracking tool
livepeer/studio pull request #2126
Opened 2024-04-04 23:11 UTC by hthillman

I promise I will set up my linter.

This tool allows us to track users through their onboarding journey.

2024-04-09 20:38 UTC, adamsoffer requested changes
Need to remove additional instances of Ripe:

https://github.com/livepeer/studio/blob/6432cc93e4f40c72baec0e0d7e820f13c22f684f/packages/www/pages/dashboard/index.tsx#L13

https://github.com/livepeer/studio/blob/6432cc93e4f40c72baec0e0d7e820f13c22f684f/packages/www/pages/dashboard/index.tsx#L15

https://github.com/livepeer/studio/blob/6432cc93e4f40c72baec0e0d7e820f13c22f684f/packages/www/pages/dashboard/index.tsx#L43

https://github.com/livepeer/studio/blob/6432cc93e4f40c72baec0e0d7e820f13c22f684f/packages/www/pages/index.tsx#L10



Also need to remove [ripe.js file](https://github.com/livepeer/studio/blob/6432cc93e4f40c72baec0e0d7e820f13c22f684f/packages/www/lib/ripe.ts):

2024-04-09 20:38 UTC, adamsoffer commented on packages/www/components/StreamDetails/MultistreamTargetsTable/index.tsx
> +    return saveDialogState.onOn;
`saveDialogState.onOn` function needs to be invoked `saveDialogState.onOn()`

2024-04-09 20:38 UTC, adamsoffer commented on packages/www/components/Header/index.tsx
> +              onClick={() => June.track(events.all.documentation)}>
The legacy behavior of the next/link component we use requires `onClick` be set on the _child_ of next/link.

2024-04-09 20:45 UTC, hthillman commented on packages/www/components/Header/index.tsx
> +              onClick={() => June.track(events.all.documentation)}>
@adamsoffer I assume this is a universal change for this PR? There are a couple other `onClick`s like this

2024-04-09 20:50 UTC, adamsoffer commented on packages/www/components/Header/index.tsx
> +              onClick={() => June.track(events.all.documentation)}>
Yeah anywhere you added an `onClick` to a `Link` component

2024-04-10 20:40 UTC, adamsoffer commented
When I navigate to a stream detail view and then refresh the page I get an error that `June` isn't available on `window`. @suhailkakar can you help debug this issue?

![CleanShot 2024-04-10 at 16 35 41@2x](https://github.com/livepeer/studio/assets/555740/414b176b-c3fe-442c-b227-6490b8fb4619)

2024-04-10 21:16 UTC, hthillman commented
> When I navigate to a stream detail view and then refresh the page I get an error that `June` isn't available on `window`. @suhailkakar can you help debug this issue?
> 
> ![CleanShot 2024-04-10 at 16 35 41@2x](https://private-user-images.githubusercontent.com/555740/321397302-414b176b-c3fe-442c-b227-6490b8fb4619.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3ODE5MzEsIm5iZiI6MTcxMjc4MTYzMSwicGF0aCI6Ii81NTU3NDAvMzIxMzk3MzAyLTQxNGIxNzZiLWMzZmUtNDQyYy1iMjI3LTY0OTBiOGZiNDYxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQyMDQwMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzMzMGNkNmEzMzJjMzk5Yjc5MzE3YzkwZTcxMDcwMTg1MmU5YjQ0NWEzNTQ1YmQyN2YwYjJhODc2OWFjOTBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fC8nGTAKKrSIkT6ZnFlCieGBOAgpkZdJZ7Uhxa8AIEs)

@adamsoffer I wonder if the `identify` call is in the wrong place, and `track` is not available until after identification. I thought I put it somewhere that would get initialized upfront every time but maybe there's a race condition

2024-04-15 13:52 UTC, suhailkakar commented
hey @hthillman 

- i've replaced the script and `window.analytics` object with the June next.js sdk[1] and a hook
- all the implementational will be same, but instead of importing June from `../lib/June`, we are using the June hook

```
import { useJune, events } from "hooks/use-june";
const June = useJune();
```

cc: @adamsoffer 

[1] https://www.june.so/docs/tracking/web/react

2024-04-15 13:53 UTC, suhailkakar commented
Also, the big "file changes" are just types issue related to livepeer/design library which is also fixed

2024-04-15 15:26 UTC, suhailkakar commented on packages/www/hooks/use-june.tsx
> +        writeKey: "3VINzqYVjfOxFyIr",
Not sure, if this needs to be added to `.env`. Please feel free to move it from here if it needs to kept private.

2024-04-17 18:22 UTC, adamsoffer approved these changes
LGTM thanks @suhailkakar !

2024-04-17 18:23 UTC, merged