link to API doc in index, add feature support matrix
livepeer/studio pull request #22
Opened 2020-08-10 03:43 UTC by ericxtang

**What does this pull request do? Explain your changes. (required)**

**Specific updates (required)**

- Link to the API doc portion from the main doc page
- Add feature support matrix

**How did you test each of these updates (required)**

Tested by clicking and proof reading

**Does this pull request close any open issues?**

**Screenshots (optional):**

**Checklist:**

- [x] I have read the **CONTRIBUTING** document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2020-08-10 19:57 UTC, darkdarkdragon requested changes

2020-08-10 19:57 UTC, darkdarkdragon commented on packages/www/pages/docs/support-matrix.mdx
> +| **Webhook Events** | `stream_started` |
```suggestion
| **Webhook Events** | `streamStarted` |
```
it is called `streamStarted` in our API

2020-08-10 19:57 UTC, darkdarkdragon commented on packages/www/pages/docs/support-matrix.mdx
> +| | Non-CDN delivery for free tier users is limited to 50mbps per stream, which roughly equals to 10 viewers in HD |
`50mbps per stream` - in our spec we have limit for number of viewers, not bandwidth

2020-08-11 14:58 UTC, ericxtang commented
@darkdarkdragon updated based on your comment.

2020-08-11 17:38 UTC, darkdarkdragon commented
@ericxtang 
`Non-CDN delivery for free tier users is limited to 50mbps per account, roughly equals to 10 viewers in HD. Additional viewers will automatically be served in 240p.`
This is no how we're planning this to work. It is like
`Non-CDN delivery for free tier users is limited to to 10 viewers per account. `

And somewhere in transcoding section:
`Free tier users will have transcoding limited to 240p after 30 free minutes`

2020-08-11 23:51 UTC, ericxtang commented
> @ericxtang
> `Non-CDN delivery for free tier users is limited to 50mbps per account, roughly equals to 10 viewers in HD. Additional viewers will automatically be served in 240p.`
> This is no how we're planning this to work. It is like
> `Non-CDN delivery for free tier users is limited to to 10 viewers per account. `
> 
> And somewhere in transcoding section:
> `Free tier users will have transcoding limited to 240p after 30 free minutes`

Thanks @darkdarkdragon.  Updated based on this comment.

2020-08-11 23:57 UTC, darkdarkdragon approved these changes
LGTM

2020-08-12 00:22 UTC, merged