With react-table (for dashboard tables also)
livepeer/studio pull request #234
Opened 2021-01-27 12:38 UTC by julianbenegas

**What does this pull request do? Explain your changes. (required)**

**Specific updates (required)**

## -

- **How did you test each of these updates (required)**

**Does this pull request close any open issues?**

**Screenshots (optional):**

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2021-01-28 20:13 UTC, adamsoffer requested changes
@julianbenegas awesome work. I don't have 100 streams created so I'm unable to test the pagination feature but everything looks GREAT.

2021-01-28 20:13 UTC, adamsoffer commented on packages/www/components/Checkbox/index.tsx
> +import { Box } from "@theme-ui/components";
Let's combine these imports `import { Box, Flex } from '@theme-ui/components'`.

2021-01-29 14:57 UTC, wohlner requested changes
For testing purposes can you change the limit to like 5 streams or something else tiny so that we can test the pagination feature?

2021-01-29 15:01 UTC, wohlner commented
I am not sure sorting is working. I am testing on https://livepeer-com-git-jb-with-react-table.livepeerorg.vercel.app/app/user. Look at the created at column, it's not in the right order when I sort it. 
<img width="1314" alt="Screen Shot 2021-01-29 at 8 59 09 AM" src="https://user-images.githubusercontent.com/7902782/106290786-782ac600-6210-11eb-88ce-d2ca30d94c4f.png">
Same goes for the name column when I sort it.
<img width="1311" alt="Screen Shot 2021-01-29 at 9 01 12 AM" src="https://user-images.githubusercontent.com/7902782/106290889-985a8500-6210-11eb-9626-7a429499be09.png">

2021-01-29 22:09 UTC, wohlner requested changes
This looks great, nice job. All the sorting, deleting, creating, and pagination works. I'd like to request two small tweaks.

1. Right now in your PR and in production on livepeer.com, we default with the most recently active stream first. Instead, let's sort with the most recently **created** stream first. It was a weird user experience for me to create a new stream and then have to click to the second page of the streams list to find it (since it was _unseen_ and never active.
2. When the page loads, can you please show how the data is being organized by default, what column is controlling the sorting? Make a down arrow next to the Created At column header like the image below.
<img width="140" alt="Screen Shot 2021-01-29 at 4 07 22 PM" src="https://user-images.githubusercontent.com/7902782/106332318-2bfd7700-624c-11eb-9621-5454fefa9916.png">

2021-02-02 19:30 UTC, wohlner approved these changes
Looks great. Just return the stream list to the original length, and this is good to go. Nice work!

2021-02-02 19:37 UTC, julianbenegas commented
Thank you @wohlner. Page size should be 100 now. Waiting for @adamsoffer before merging!

2021-02-02 19:45 UTC, adamsoffer approved these changes
LGTM!

2021-02-02 19:46 UTC, merged