webhook Cannon
livepeer/studio pull request #390
Opened 2021-05-11 10:26 UTC by ya7ya

**What does this pull request do? Explain your changes. (required)**

implements #378 

**Specific updates (required)**
- create the queue object
- add the methods for `emitting` and `popping` an event

## -

- **How did you test each of these updates (required)**

**Does this pull request close any open issues?**

**Screenshots (optional):**

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2021-05-25 16:43 UTC, iameli requested changes
Per discussion, let's have each webhook entry add its own entry to the queue

2021-05-25 16:43 UTC, iameli commented on packages/api/src/store/queue.ts
> +    if (!opts.useReplica) {
Don't think we can probably `useReplica` here, cuz we're locking stuff

2021-05-25 16:43 UTC, iameli commented on packages/api/src/schema/schema.yaml
> +  - name: webhookResponse
Probably `webhook-response`

2021-05-25 16:43 UTC, iameli commented on packages/api/src/webhooks/cannon.ts
> +    event.reteries = event.reteries ? event.reteries + 1 : 1;
`retries`

2021-05-25 16:43 UTC, iameli commented on packages/api/src/webhooks/cannon.ts
> +    await this.db.webhookResponse.create({
It would be awesome to have a `duration` field on here too

2021-05-25 16:43 UTC, iameli commented on packages/api/src/webhooks/cannon.ts
> +      return;
Could throw an error here

2021-05-25 16:43 UTC, iameli commented on packages/api/src/webhooks/cannon.ts
> +    let user = await this.store.get(`user/${event.userId}`);
`this.db.user.get`

2021-05-25 16:43 UTC, iameli commented on packages/api/src/webhooks/cannon.ts
> +            );
Can put a `throw` here and lose the `else` statement

2021-05-25 16:43 UTC, iameli commented on packages/api/src/webhooks/cannon.ts
> +              this.storeResponse(webhook, event, resp);
`await`?

2021-05-25 16:43 UTC, iameli commented on packages/api/src/webhooks/cannon.ts
> +              this.retry(event);
Can get rid of this when we move to a single hook per

2021-05-25 19:00 UTC, darkdarkdragon commented
@ya7ya @iameli 
BTW, maybe we should tie webhook (message queue in general?) processing to the region?
Firing webhook from API server in Singapore to the receiver in Latin America is not the optimal thing to do...

2021-06-03 23:03 UTC, darkdarkdragon requested changes

2021-06-03 23:03 UTC, darkdarkdragon commented on packages/api/src/webhooks/cannon.ts
> +      this.db.queue.setMsgHandler(this.processEvent.bind(this));
We should also drain pending events at start.

2021-06-03 23:03 UTC, darkdarkdragon commented on packages/api/src/webhooks/cannon.ts
> +    let user = await this.db.user.get(`user/${event.userId}`);
```suggestion
    let user = await this.db.user.get(event.userId);
```
Also, what would happen if user is not found?

2021-06-03 23:03 UTC, darkdarkdragon commented on packages/api/src/webhooks/cannon.ts
> +    if (!event) {
We also need to check that event structure is valid (has all required fields at least).

2021-06-07 16:09 UTC, merged