WIP: postgres refactor
livepeer/studio pull request #43
Opened 2020-08-20 08:33 UTC by iameli

2020-08-24 10:00 UTC, ya7ya commented
@iameli Nice work dude, Quick question, Is there some db initialization required before running the tests beside `yarn postgres:start` ?

2020-08-24 17:59 UTC, iameli commented
@ya7ya There shouldn't be — `ensureDatabase` and `ensureTable` handle the necessary creation. Let me know if you're seeing problems though, that could be an issue

2020-08-24 23:00 UTC, darkdarkdragon requested changes
Couple of changes, though not finished review yet.

2020-08-24 23:00 UTC, darkdarkdragon commented on packages/api/src/controllers/stream.js
> +  if (newCursor.length > 0) {
Error?

2020-08-24 23:00 UTC, darkdarkdragon commented on packages/api/src/controllers/stream.js
> +    await req.store.get(`object-store/${req.body.objectStoreId}`)
Result of this call is not used anywhere.

2020-08-24 23:00 UTC, darkdarkdragon commented on packages/api/src/controllers/stream.js
> +      req.user.id,
this is bug in webhooks that was fixed by Yahya, need to revert this line

2020-08-24 23:00 UTC, darkdarkdragon commented on packages/api/src/controllers/webhook.js
> +    const [output, newCursor] = db.stream.find([`data->>'deleted' IS NULL`])
This makes call six lines up unnecessary.

2020-08-25 01:14 UTC, darkdarkdragon requested changes
Two more small comments, plus made PR with some fixes https://github.com/livepeer/livepeer-com/pull/50

Otherwise looks good!

2020-08-25 01:14 UTC, darkdarkdragon commented on packages/api/src/store/table.ts
> +  db: DB
`DB` here refers to the instance of DB class, not to a class itself

2020-08-25 01:14 UTC, darkdarkdragon commented on packages/api/src/store/table.ts
> +      sql`SELECT data FROM `.append(this.name).append(sql` WHERE id=${id}`),
```suggestion
      sql`SELECT data FROM `.append(this.name).append(sql` WHERE id=${id}`.setName(`${this.name}_by_id`)),
```
to use Postres prepared statement

2020-08-25 02:18 UTC, iameli commented on packages/api/src/controllers/stream.js
> +  if (newCursor.length > 0) {
oh yeah. hm.

2020-08-25 02:43 UTC, iameli commented on packages/api/src/store/table.ts
> +  db: DB
fixed by tweaking the import

2020-08-25 06:25 UTC, merged