Jb/date boolean filters
livepeer/studio pull request #480
Opened 2021-06-24 17:14 UTC by julianbenegas

closes #438

2021-06-24 22:22 UTC, adamsoffer requested changes
![image](https://user-images.githubusercontent.com/555740/123339720-13526e00-d519-11eb-8235-aa1245cd5d38.png)

Can we remove the empty row when "Is Active" is checked?

Or if it's easier, add two checkboxes like this:
![image](https://user-images.githubusercontent.com/555740/123339902-6c220680-d519-11eb-9494-38848deed2cf.png)

2021-06-24 22:23 UTC, julianbenegas commented on packages/www/components/Dashboard/TokenTable/index.tsx
> +      {/* TODO fix this before merging! @julianbenegas */}
```suggestion
```

2021-06-24 22:30 UTC, julianbenegas commented
> Can we remove the empty row when "Is Active" is checked?
> 
> Or if it's easier, add two checkboxes like this:

@adamsoffer The second option is best, because the first option "Can we remove the empty row when "Is Active" is checked?" would not cover all the filter cases. (`undefined`, `true`, `false`).

But, on the stripe design, they look like checkboxes, but they are actually radio buttons 🤔

2021-06-24 22:33 UTC, adamsoffer commented
> But, on the stripe design, they look like checkboxes, but they are actually radio buttons 🤔

Oh yeah, radio buttons are probably more appropriate. Can look something like this:

![image](https://user-images.githubusercontent.com/555740/123340737-b8217b00-d51a-11eb-99bd-3b7f921698e5.png)

2021-06-25 16:50 UTC, adamsoffer commented
Nice. Let's just convert those radios back to checkboxes. And by default neither "Active" nor "Idle" should be checked when  "Status" is checked.

2021-06-26 17:21 UTC, adamsoffer commented
Going to merge this so you can create a new branch for the remaining pieces (adding total results, initializing the cursor so pagination works, and adjusting the status dropdown).

2021-06-26 17:21 UTC, adamsoffer approved these changes

2021-06-26 17:22 UTC, merged