Rest of react query implementation
livepeer/studio pull request #509
Opened 2021-07-02 18:57 UTC by emilianoyaryura

**What does this pull request do? Explain your changes. (required)**

**Specific updates (required)**

## -

- **How did you test each of these updates (required)**

**Does this pull request close any open issues?**

**Screenshots (optional):**

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2021-07-02 21:40 UTC, julianbenegas requested changes

2021-07-02 21:40 UTC, julianbenegas commented on packages/www/pages/dashboard/developers/webhooks/[id].tsx
> +                            queryClient.invalidateQueries();
we don't want to invalidate ALL queries across the app. We should pass the queryKey to `invalidateQueries`

2021-07-02 21:40 UTC, julianbenegas commented on packages/www/pages/dashboard/developers/webhooks/[id].tsx
> +                            queryClient.invalidateQueries();
Also, we should `await` this, if `invalidateQueries` returns a promise.

2021-07-02 21:40 UTC, julianbenegas commented on packages/www/pages/dashboard/developers/webhooks/[id].tsx
> +                      await queryClient.invalidateQueries();
same: missing queryKey

2021-07-02 21:40 UTC, julianbenegas commented on packages/www/pages/dashboard/streams/[id]/index.tsx
> +                      revalidate={queryClient.invalidateQueries()}
We want to pass the `invalidateQueries` method down, but _not_ execute it...

This is executing `invalidateQueries` and passing down whatever it gets in return.

2021-07-02 21:40 UTC, julianbenegas commented on packages/www/pages/dashboard/streams/[id]/index.tsx
> +                      revalidate={queryClient.invalidateQueries()}
Also, same as comments above: we don't want to invalidate ALL the queries.

2021-07-05 17:47 UTC, adamsoffer approved these changes
LGTM!

2021-07-05 17:48 UTC, merged