Issue 220 - added some contextual copy to Errors /docs page
livepeer/studio pull request #672
Opened 2021-10-26 08:18 UTC by FullStackTiger

**What does this pull request do? Explain your changes. (required)**

**Specific updates (required)**

- Add some contextual copy to Errors /docs page

**Does this pull request close any open issues?**

- Fixes Add some contextual copy to Errors /docs page

**Screenshots (optional):**

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2021-10-26 15:34 UTC, victorges requested changes

2021-10-26 15:34 UTC, victorges commented on packages/www/docs/api-reference/errors.mdx
> +page to leave us a message.
I think we don't have a chat in our website. WDYT of suggesting sending an email to our support instead? We have this email listed in our "Contact" page hello@livepeer.com, but maybe there is something more specific like support@livepeer.com that works?

2021-10-26 16:46 UTC, pglowacky commented on packages/www/docs/api-reference/errors.mdx
> +page to leave us a message.
We do have a chat, but it's not always staffed (sometimes, I'm sleeping 😆). Best to have people email us at hello@livepeer.com -- that is probably the fastest way to get someone's attention.

2021-10-26 16:49 UTC, pglowacky requested changes

2021-10-26 16:49 UTC, pglowacky commented on packages/www/docs/api-reference/errors.mdx
> +page to leave us a message.
I'd prefer: "If you encounter an error that could use our team's attention, please email us at hello@livepeer.com"

2021-10-26 16:49 UTC, victorges commented on packages/www/docs/api-reference/errors.mdx
> +page to leave us a message.
Hmmm interesting, never seen it actually. Does it show up in every page? I accessed this API errors doc and didn't find any buttn for it

2021-10-27 17:16 UTC, FullStackTiger commented
updated the text, added this mailto link for the email address @victorges

2021-10-27 17:45 UTC, victorges approved these changes
Awesome!

2021-10-27 17:52 UTC, merged