Add recaptcha v3 to sign up form
livepeer/studio pull request #732
Opened 2021-11-17 10:17 UTC by FullStackTiger

**What does this pull request do? Explain your changes. (required)**

**Specific updates (required)**

- Add recaptcha v3 to sign up form

**Does this pull request close any open issues?**

- Fixes #699

**Screenshots (optional):**

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2021-11-19 19:02 UTC, iameli requested changes
A few tweaks

2021-11-19 19:02 UTC, iameli commented on packages/www/layouts/recaptcha.jsx
> +  };
Any reason to have this as a class component instead of another function component?
```suggestion
  return (props) => (
    <Recaptcha>
      <Component {...props} />
    </Recaptcha>
  );
```

2021-11-19 19:02 UTC, iameli commented on packages/www/pages/register.tsx
> +      setLoading(true);
Let's move this above the `await executeRecaptcha("register");` line — that will stop the user from accidentally submitting twice while we're waiting for that function to come back

2021-11-19 19:02 UTC, iameli commented on packages/www/pages/register.tsx
> +    } catch (err) {
Seems like we should either remove this block or change it to `setErrors` so we don't just fail silently

2021-11-24 02:22 UTC, adamsoffer approved these changes
LGTM! Let's squash and merge and do a thorough test on livepeer.monster.

2021-11-24 15:26 UTC, merged

2021-11-25 17:09 UTC, victorges commented
Hey @FullStackTiger this change seems to have broken the API build/tests. Could you take a look at it?

2021-11-25 17:34 UTC, FullStackTiger commented
Ah, I will check it @victorges

2021-11-29 09:01 UTC, FullStackTiger commented
I created one pr @victorges 
https://github.com/livepeer/livepeer-com/runs/4351112133?check_suite_focus=true